// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCConfigurationTool.DataModel;

namespace PCConfigurationTool.DataModel.Migrations
{
    [DbContext(typeof(PCConfigurationContext))]
    [Migration("20211121212422_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCConfigurationTool.DataModel.CPU", b =>
                {
                    b.Property<int>("CPUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoreCount")
                        .HasColumnType("int");

                    b.Property<string>("IntegratedGraphics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceCoreClock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CPUId");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            CPUId = 1,
                            CoreCount = 6,
                            Name = "AMD Ryzen 5 5600X",
                            PerformanceCoreClock = "3.7 GHz",
                            Price = 294.00m
                        },
                        new
                        {
                            CPUId = 2,
                            CoreCount = 8,
                            Name = "AMD Ryzen 7 5800X",
                            PerformanceCoreClock = "3.8 GHz",
                            Price = 341.66m
                        },
                        new
                        {
                            CPUId = 3,
                            CoreCount = 6,
                            IntegratedGraphics = "Radeon Vega 7",
                            Name = "AMD Ryzen 5 5600G",
                            PerformanceCoreClock = "3.9 GHz",
                            Price = 239.00m
                        },
                        new
                        {
                            CPUId = 4,
                            CoreCount = 10,
                            IntegratedGraphics = "Intel UHD Graphics 630",
                            Name = "Intel Core i9-10900K",
                            PerformanceCoreClock = "3.7 GHz",
                            Price = 458.99m
                        },
                        new
                        {
                            CPUId = 5,
                            CoreCount = 6,
                            Name = "Intel Core i5-11400F",
                            PerformanceCoreClock = "2.6 GHz",
                            Price = 198.00m
                        },
                        new
                        {
                            CPUId = 6,
                            CoreCount = 8,
                            Name = "AMD Ryzen 7 1800X",
                            PerformanceCoreClock = "3.6 GHz",
                            Price = 430.56m
                        });
                });

            modelBuilder.Entity("PCConfigurationTool.DataModel.Motherboard", b =>
                {
                    b.Property<int>("MotherboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemoryMax")
                        .HasColumnType("int");

                    b.Property<int>("MemorySlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MotherboardId");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            MotherboardId = 1,
                            MemoryMax = 128,
                            MemorySlots = 4,
                            Name = "Asus TUF GAMING X570-PLUS (WI-FI)",
                            Price = 194.99m
                        },
                        new
                        {
                            MotherboardId = 2,
                            MemoryMax = 128,
                            MemorySlots = 4,
                            Name = "MSI PRO Z690-A DDR4",
                            Price = 209.99m
                        },
                        new
                        {
                            MotherboardId = 3,
                            MemoryMax = 256,
                            MemorySlots = 8,
                            Name = "Asus ROG ZENITH II EXTREME ALPHA",
                            Price = 870.99m
                        },
                        new
                        {
                            MotherboardId = 4,
                            MemoryMax = 64,
                            MemorySlots = 2,
                            Name = "ASRock Fatal1ty B450 Gaming-ITX/ac",
                            Price = 99.99m
                        },
                        new
                        {
                            MotherboardId = 5,
                            MemoryMax = 2000,
                            MemorySlots = 16,
                            Name = "Supermicro MBD-X10DAX",
                            Price = 564.25m
                        },
                        new
                        {
                            MotherboardId = 6,
                            MemoryMax = 128,
                            MemorySlots = 4,
                            Name = "Gigabyte B560 AORUS PRO AX",
                            Price = 219.99m
                        },
                        new
                        {
                            MotherboardId = 7,
                            MemoryMax = 128,
                            MemorySlots = 4,
                            Name = "ASRock Z590M Pro4",
                            Price = 129.99m
                        });
                });

            modelBuilder.Entity("PCConfigurationTool.DataModel.RAM", b =>
                {
                    b.Property<int>("RAMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RAMId");

                    b.ToTable("RAM");

                    b.HasData(
                        new
                        {
                            RAMId = 1,
                            Memory = 16,
                            Name = "Corsair Vengeance LPX",
                            Price = 67.81m
                        },
                        new
                        {
                            RAMId = 2,
                            Memory = 32,
                            Name = "G.Skill Ripjaws V Series",
                            Price = 114.97m
                        },
                        new
                        {
                            RAMId = 3,
                            Memory = 64,
                            Name = "G.Skill Trident Z RGB",
                            Price = 305.99m
                        },
                        new
                        {
                            RAMId = 4,
                            Memory = 128,
                            Name = "G.Skill Trident Z Royal",
                            Price = 1159.00m
                        },
                        new
                        {
                            RAMId = 5,
                            Memory = 16,
                            Name = "ADATA XPG Z1",
                            Price = 49.99m
                        },
                        new
                        {
                            RAMId = 6,
                            Memory = 8,
                            Name = "Corsair Vengeance LPX",
                            Price = 32.99m
                        },
                        new
                        {
                            RAMId = 7,
                            Memory = 16,
                            Name = "Crucial Ballistix RGB",
                            Price = 74.98m
                        },
                        new
                        {
                            RAMId = 8,
                            Memory = 256,
                            Name = "Corsair Vengeance RGB Pro",
                            Price = 1309.99m
                        });
                });

            modelBuilder.Entity("PCConfigurationTool.DataModel.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cache")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StorageId");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            StorageId = 1,
                            Cache = "256 MB",
                            Capacity = 2000,
                            Name = "Seagate Barracuda Compute",
                            Price = 46.99m
                        },
                        new
                        {
                            StorageId = 2,
                            Cache = "1024 MB",
                            Capacity = 1000,
                            Name = "Samsung 970 Evo Plus",
                            Price = 136.94m
                        },
                        new
                        {
                            StorageId = 3,
                            Capacity = 15300,
                            Name = "Team QX",
                            Price = 3461.99m
                        },
                        new
                        {
                            StorageId = 4,
                            Capacity = 8000,
                            Name = "Sabrent Rocket Q",
                            Price = 1299.99m
                        },
                        new
                        {
                            StorageId = 5,
                            Cache = "512 MB",
                            Capacity = 18000,
                            Name = "Western Digital Gold",
                            Price = 485.99m
                        },
                        new
                        {
                            StorageId = 6,
                            Capacity = 1000,
                            Name = "Team MP33",
                            Price = 72.98m
                        },
                        new
                        {
                            StorageId = 7,
                            Cache = "8 MB",
                            Capacity = 320,
                            Name = "Toshiba MQ01ABD032",
                            Price = 14.80m
                        },
                        new
                        {
                            StorageId = 8,
                            Cache = "2048 MB",
                            Capacity = 2000,
                            Name = "Samsung 870 Evo",
                            Price = 235.48m
                        });
                });

            modelBuilder.Entity("PCConfigurationTool.DataModel.VideoCard", b =>
                {
                    b.Property<int>("VideoCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VideoCardId");

                    b.ToTable("VideoCards");

                    b.HasData(
                        new
                        {
                            VideoCardId = 1,
                            Chipset = "GeForce RTX 3060",
                            Memory = 12,
                            Name = "EVGA XC GAMING",
                            Price = 915.99m
                        },
                        new
                        {
                            VideoCardId = 2,
                            Chipset = "GeForce RTX 3060",
                            Memory = 12,
                            Name = "MSI GAMING X",
                            Price = 949.99m
                        },
                        new
                        {
                            VideoCardId = 3,
                            Chipset = "GeForce GTX 1660 SUPER",
                            Memory = 6,
                            Name = "Asus TUF GAMING OC",
                            Price = 649.95m
                        },
                        new
                        {
                            VideoCardId = 4,
                            Chipset = "GeForce RTX 3080 Ti",
                            Memory = 12,
                            Name = "EVGA FTW3 ULTRA GAMING LE iCX3",
                            Price = 2492.98m
                        },
                        new
                        {
                            VideoCardId = 5,
                            Chipset = "Radeon RX 6600 XT",
                            Memory = 8,
                            Name = "XFX Speedster QICK 308 Black",
                            Price = 821.79m
                        },
                        new
                        {
                            VideoCardId = 6,
                            Chipset = "Radeon RX 580",
                            Memory = 8,
                            Name = "XFX GTR XXX",
                            Price = 865.99m
                        },
                        new
                        {
                            VideoCardId = 7,
                            Chipset = "GeForce GT 1030",
                            Memory = 2,
                            Name = "Asus GT1030-2G-CSM",
                            Price = 137.68m
                        },
                        new
                        {
                            VideoCardId = 8,
                            Chipset = "GeForce RTX 3090",
                            Memory = 24,
                            Name = "Gigabyte AORUS XTREME WATERFORCE",
                            Price = 3490.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
